// <auto-generated />
using System;
using GameEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameEngine.Migrations
{
    [DbContext(typeof(GameEngineContext))]
    [Migration("20230117091958_new-models-20")]
    partial class newmodels20
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardDeck", b =>
                {
                    b.Property<int>("DecksId")
                        .HasColumnType("int");

                    b.Property<int>("CardsSymbol")
                        .HasColumnType("int");

                    b.Property<int>("CardsType")
                        .HasColumnType("int");

                    b.HasKey("DecksId", "CardsSymbol", "CardsType");

                    b.HasIndex("CardsSymbol", "CardsType");

                    b.ToTable("CardDeck");
                });

            modelBuilder.Entity("CardPlayer", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("int");

                    b.Property<int>("CardsSymbol")
                        .HasColumnType("int");

                    b.Property<int>("CardsType")
                        .HasColumnType("int");

                    b.HasKey("PlayersId", "CardsSymbol", "CardsType");

                    b.HasIndex("CardsSymbol", "CardsType");

                    b.ToTable("CardPlayer");
                });

            modelBuilder.Entity("CardPokerTable", b =>
                {
                    b.Property<int>("TablesId")
                        .HasColumnType("int");

                    b.Property<int>("CardsSymbol")
                        .HasColumnType("int");

                    b.Property<int>("CardsType")
                        .HasColumnType("int");

                    b.HasKey("TablesId", "CardsSymbol", "CardsType");

                    b.HasIndex("CardsSymbol", "CardsType");

                    b.ToTable("CardPokerTable");
                });

            modelBuilder.Entity("GameEngine.Core.Services.Webhook.SubscribeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<string>("UserSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Subscribe");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accessory");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Card", b =>
                {
                    b.Property<int>("Symbol")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Symbol", "Type");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Deck");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Chips")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBet")
                        .HasColumnType("int");

                    b.Property<bool>("IsFolded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PokerTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokerTableId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Chips")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Table");
                });

            modelBuilder.Entity("GameEngine.Models.Game.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChipsAquired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserSecret")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CardDeck", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Deck", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsSymbol", "CardsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardPlayer", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsSymbol", "CardsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardPokerTable", b =>
                {
                    b.HasOne("GameEngine.Models.Game.PokerTable", null)
                        .WithMany()
                        .HasForeignKey("TablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsSymbol", "CardsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEngine.Core.Services.Webhook.SubscribeModel", b =>
                {
                    b.HasOne("GameEngine.Models.Game.PokerTable", "Table")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Accessory", b =>
                {
                    b.HasOne("GameEngine.Models.Game.User", null)
                        .WithMany("Accessories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEngine.Models.Game.Player", b =>
                {
                    b.HasOne("GameEngine.Models.Game.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.PokerTable", null)
                        .WithMany("Players")
                        .HasForeignKey("PokerTableId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Player", "Owner")
                        .WithOne("Table")
                        .HasForeignKey("GameEngine.Models.Game.PokerTable", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Player", b =>
                {
                    b.Navigation("Table")
                        .IsRequired();
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("GameEngine.Models.Game.User", b =>
                {
                    b.Navigation("Accessories");
                });
#pragma warning restore 612, 618
        }
    }
}
