// <auto-generated />
using GameEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameEngine.Migrations
{
    [DbContext(typeof(GameEngineContext))]
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
    [Migration("20230116111532_new-models-11")]
    partial class newmodels11
========
    [Migration("20230114143104_startup")]
    partial class startup
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs

            modelBuilder.Entity("CardDeck", b =>
                {
                    b.Property<int>("DecksId")
                        .HasColumnType("int");

                    b.Property<int>("CardsSymbol")
                        .HasColumnType("int");

                    b.Property<int>("CardsType")
                        .HasColumnType("int");

                    b.HasKey("DecksId", "CardsSymbol", "CardsType");

                    b.HasIndex("CardsSymbol", "CardsType");

                    b.ToTable("CardDeck");
                });

            modelBuilder.Entity("CardPlayer", b =>
                {
                    b.Property<int>("PlayersId")
                        .HasColumnType("int");

                    b.Property<int>("CardsSymbol")
                        .HasColumnType("int");

                    b.Property<int>("CardsType")
                        .HasColumnType("int");

                    b.HasKey("PlayersId", "CardsSymbol", "CardsType");

                    b.HasIndex("CardsSymbol", "CardsType");

                    b.ToTable("CardPlayer");
                });

            modelBuilder.Entity("CardPokerTable", b =>
                {
                    b.Property<int>("TablesId")
                        .HasColumnType("int");

                    b.Property<int>("CardsSymbol")
                        .HasColumnType("int");

                    b.Property<int>("CardsType")
                        .HasColumnType("int");

                    b.HasKey("TablesId", "CardsSymbol", "CardsType");

                    b.HasIndex("CardsSymbol", "CardsType");

                    b.ToTable("CardPokerTable");
                });
========
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs

            modelBuilder.Entity("GameEngine.Models.Game.Accessory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accessory");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Card", b =>
                {
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
========
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                    b.Property<int>("Symbol")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Symbol", "Type");

                    b.ToTable("Card");
                });

<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
            modelBuilder.Entity("GameEngine.Models.Game.Deck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Deck");
========
            modelBuilder.Entity("GameEngine.Models.Game.DeckCard", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.HasKey("CardId", "TableId");

                    b.HasIndex("TableId");

                    b.ToTable("DeckCards");
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                });

            modelBuilder.Entity("GameEngine.Models.Game.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChipsValue")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBet")
                        .HasColumnType("int");

                    b.Property<bool>("IsFolded")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
========

                    b.Property<int?>("PokerTableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokerTableId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PlayerCard", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("CardId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerCards");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChipsValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("GameEngine.Models.Game.TableCard", b =>
                {
                    b.Property<int>("CardId")
                        .HasColumnType("int");
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Chips")
                        .HasColumnType("int");

                    b.Property<int>("DeckId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.ToTable("Table");
                });

            modelBuilder.Entity("GameEngine.Models.Game.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChipsAquired")
                        .HasColumnType("int");

                    b.Property<string>("Name")
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
========
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("UserIdentifier")
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
            modelBuilder.Entity("CardDeck", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Deck", null)
                        .WithMany()
                        .HasForeignKey("DecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsSymbol", "CardsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardPlayer", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsSymbol", "CardsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CardPokerTable", b =>
                {
                    b.HasOne("GameEngine.Models.Game.PokerTable", null)
                        .WithMany()
                        .HasForeignKey("TablesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Card", null)
                        .WithMany()
                        .HasForeignKey("CardsSymbol", "CardsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

========
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
            modelBuilder.Entity("GameEngine.Models.Game.Accessory", b =>
                {
                    b.HasOne("GameEngine.Models.Game.User", null)
                        .WithMany("Accessories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameEngine.Models.Game.Player", b =>
                {
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
                    b.HasOne("GameEngine.Models.Game.PokerTable", "Table")
                        .WithMany("Players")
========
                    b.HasOne("GameEngine.Models.Game.Card", "Card")
                        .WithMany("Decks")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.PokerTable", "PokerTable")
                        .WithMany("CardDeck")
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
                    b.Navigation("Table");
========
                    b.Navigation("Card");

                    b.Navigation("PokerTable");
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
                    b.HasOne("GameEngine.Models.Game.Deck", "Deck")
========
                    b.HasOne("GameEngine.Models.Game.PokerTable", null)
                        .WithMany("Players")
                        .HasForeignKey("PokerTableId");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PlayerCard", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Card", "Card")
                        .WithMany("Players")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.Player", "Player")
                        .WithMany("Cards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GameEngine.Models.Game.TableCard", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Card", "Card")
                        .WithMany("Tables")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameEngine.Models.Game.PokerTable", "PokerTable")
                        .WithMany("Cards")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("PokerTable");
                });

            modelBuilder.Entity("GameEngine.Models.Game.User", b =>
                {
                    b.HasOne("GameEngine.Models.Game.Player", "Player")
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.Navigation("Players");
<<<<<<<< HEAD:GameEngineApi/GameEngine/Migrations/20230116111532_new-models-11.Designer.cs
========

                    b.Navigation("Tables");
                });

            modelBuilder.Entity("GameEngine.Models.Game.Player", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("GameEngine.Models.Game.PokerTable", b =>
                {
                    b.Navigation("CardDeck");

                    b.Navigation("Cards");

                    b.Navigation("Players");
>>>>>>>> gameManagerFlow:GameEngineApi/GameEngine/Migrations/20230114143104_startup.Designer.cs
                });

            modelBuilder.Entity("GameEngine.Models.Game.User", b =>
                {
                    b.Navigation("Accessories");
                });
#pragma warning restore 612, 618
        }
    }
}
